with SubmarineSubSystem; use SubmarineSubSystem;
with Ada.Text_IO; use Ada.Text_IO;

procedure Main is
begin
   StartSubmarine;
   Put_Line("Nuclear Submarine is: ");
   Put_Line(NuclearSubmarine.GoodToGo'Image);
   Put_Line("Try Starting Submarine");
   StartSubmarine;
   Put_Line("Now Nuclear Submarine is: ");
   Put_Line(NuclearSubmarine.GoodToGo'Image);
   Put_Line("Can we Fire? ");
   SubmarineAction;
   Put_Line(NuclearSubmarine.OpTest'Image);
   Put_Line("Need to Close Both Doors to be operational: ");
   Put_Line("Airlock Door one is: ");
   Put_Line(NuclearSubmarine.ClosingOne'Image);
   Put_Line("Airlock Door two is: ");
   Put_Line(NuclearSubmarine.ClosingTwo'Image);
   Put_Line("TEST FOR BOTH DOORS CAN'T BE OPEN!");
   D2Open;
   Put_Line("Airlock Door one is: ");
   Put_Line(NuclearSubmarine.ClosingOne'Image);
   Put_Line("Airlock Door two is: ");
   Put_Line(NuclearSubmarine.ClosingTwo'Image);
   Put_Line("Airlock Door two cannot be Open if Airlock Door one is Open");
   Put_Line("NOW TEST DOOR 1 & 2 OPEN/CLOSE IN VICE VERSA!");
   D1Close;
   D2Close;
   D2Open;
   D1Open;
   Put_Line("Airlock Door one is: ");
   Put_Line(NuclearSubmarine.ClosingOne'Image);
   Put_Line("Airlock Door two is: ");
   Put_Line(NuclearSubmarine.ClosingTwo'Image);
   Put_Line("Airlock Door one cannot be Open if Airlock Door two is Open");
   Put_Line("END OF TEST");
   Put_Line("Closing Airlock Door one: ");
   D1Close;
   Put_Line("Airlock Door one is: ");
   Put_Line(NuclearSubmarine.ClosingOne'Image);
   Put_Line("Closing Airlock Door two: ");
   D2Close;
   Put_Line("Airlock Door two is: ");
   Put_Line(NuclearSubmarine.ClosingTwo'Image);
   Put_Line("Is Nuclear Submarin operational yet: ");
   StartSubmarine;
   Put_Line(NuclearSubmarine.GoodToGo'Image);
   Put_Line("Can we Fire?");
   SubmarineAction;
   Put_Line(NuclearSubmarine.OpTest'Image);
   Put_Line("Need to Lock Both Doors to be operational: ");
   Put_Line("Priming for Airlock Door locking: ");
   Put_Line("Airlock Door one lock is: ");
   Put_Line(NuclearSubmarine.LockingOne'Image);
   Put_Line("Airlock Door two lock is: ");
   Put_Line(NuclearSubmarine.LockingTwo'Image);
   Put_Line("Initiate Locking: ");
   D1Lock;
   D2Lock;
   Put_Line("Airlock Door one is: ");
   Put_Line(NuclearSubmarine.LockingOne'Image);
   Put_Line("Airlock Door two is: ");
   Put_Line(NuclearSubmarine.LockingTwo'Image);
   Put_Line("Try Opening Airlock Door one: ");
   D1Open;
   Put_Line("Status of Airlock Door one: ");
   Put_Line(NuclearSubmarine.ClosingOne'Image);
   Put_Line(NuclearSubmarine.LockingOne'Image);
   Put_Line("Lock secure!");
   Put_Line("Try Opening Airlock Door Two: ");
   D2Open;
   Put_Line("Status of Airlock Door Two: ");
   Put_Line(NuclearSubmarine.ClosingTwo'Image);
   Put_Line(NuclearSubmarine.LockingTwo'Image);
   Put_Line("Lock secure!");
   Put_Line("Is Nuclear Submarine Operational: ");
   StartSubmarine;
   Put_Line(NuclearSubmarine.GoodToGo'Image);
   Put_Line("Can we Fire?");
   SubmarineAction;
   Put_Line(NuclearSubmarine.OpTest'Image);
   Put_Line("SUBMARINE IS NOW OPERATIONAL TO TEST ALL SYSTEMS!");
   Put_Line("");
   Put_Line("");
   Put_Line("");
   Put_Line("DIVE AND DEPTH CHECK TEST!");
   Put_Line("Ready to Dive, Commence Divining");
   DiveOrNot;
   Put_Line(NuclearSubmarine.DDive'Image);
   Put_Line("State of Dive?");
   DepthMeterCheck;
   Put_Line(NuclearSubmarine.DStage'Image);
   Put_Line("Dive by 3!");
   ChangeDepth;
   Put_Line("Depth is now: ");
   Put_Line(NuclearSubmarine.DLevel'Image);
   Put("Submarine in Okay Depth Stage? "); -- Displays Submarine depth state while
   DepthMeterCheck;                        -- This line is printed... Don't know why.
   Put_Line(NuclearSubmarine.DStage'Image);
   Put_Line("Dive by 3!");
   ChangeDepth;
   Put_Line("Depth is now: ");
   Put_Line(NuclearSubmarine.DLevel'Image);
   Put("Submarine in Okay Depth Stage? ");
   DepthMeterCheck;
   Put_Line(NuclearSubmarine.DStage'Image);
   Put_Line("Dive by 3!");
   ChangeDepth;
   Put_Line("Depth is now: ");
   Put_Line(NuclearSubmarine.DLevel'Image);
   Put("Submarine in Okay Depth Stage? ");
   DepthMeterCheck;
   Put_Line(NuclearSubmarine.DStage'Image);
   Put_Line("Dive by 3!");
   ChangeDepth;
   Put_Line("Depth is now: ");
   Put_Line(NuclearSubmarine.DLevel'Image);
   Put("Submarine in Okay Depth Stage? ");
   DepthMeterCheck;
   Put_Line(NuclearSubmarine.DStage'Image);
   Put_Line("Cannot Dive any deeper!");
   Put_Line("Taking Submarine back to Surface");
   Resurface;
   Put_Line("Submarine is: ");
   Put_Line(NuclearSubmarine.DDive'Image);
   Put_Line("Submarine Depth level is: ");
   Put_Line(NuclearSubmarine.DLevel'Image);
   Put_Line("TEST IF SUBMARINE CAN CHANGE DEPTH WHILE SURFACED");
   ChangeDepth;
   ChangeDepth;
   ChangeDepth;
   Put_Line(NuclearSubmarine.DLevel'Image);
   Put_Line("IT CANNOT! TEST OVER");
   Put_Line("");
   Put_Line("");
   Put_Line("");
   Put_Line("DIVE AND USE OXYGEN TEST");
   Put_Line("Submarine is: ");
   Put_Line(NuclearSubmarine.DDive'Image);
   Put_Line("Dive Submarine!");
   DiveOrNot;
   Put_Line("Submarine is: ");
   Put_Line(NuclearSubmarine.DDive'Image);
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Submarine Oxygen Reserves are: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("State of Oxygen Tank is ");
   OxygenReserveCheck;
   Put_Line(NuclearSubmarine.OState'Image);
   Put_Line("Use Oxygen: ");
   ConsumeOxygen;
   Put_Line("Is Submarine defently Surfaced? ");
   Put_Line(NuclearSubmarine.DDive'Image);
   Put_Line("Check if Oxygen Reserves have been restored by resurficing: ");
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("Can Oxygen be consumed while surfaced? ");
   ConsumeOxygen;
   Put_Line(NuclearSubmarine.OTank'Image);
   Put_Line("No it cannot ");
   Put_Line("THIS ENDS TESTING FOR OXYGEN SYSTEM!");
   Put_Line("");
   Put_Line("");
   Put_Line("");
   Put_Line("BEGIN TESTING REACTOR OVERHEATING SYSTEMS");
   Put_Line("Submarin must Dive");
   DiveOrNot;
   Put_Line(NuclearSubmarine.DDive'Image);
   Put_Line("Overheat Reactor: ");
   ReactorOverheatRoutine;
   Put_Line("Submarine state is still: ");
   Put_Line(NuclearSubmarine.RTemp'Image);
   Put_Line("Can we dive?");
   DiveOrNot;
   Put_Line(NuclearSubmarine.DDive'Image);
   Put_Line("Submarine cannot diver because reactor is still: ");
   Put_Line(NuclearSubmarine.RTemp'Image);
   Put_Line("Intiate Cooling of the reactor: ");
   CoolReactor;
   Put_Line("Reactor is now: ");
   Put_Line(NuclearSubmarine.RTemp'Image);
   Put_Line("Can we dive?");
   DiveOrNot;
   Put_Line(NuclearSubmarine.DDive'Image);
   Put_Line("THIS ENDS TESTING FOR REACTOR SUBSYSTEMS");
   Put_Line("");
   Put_Line("");
   Put_Line("");
   Put_Line("BEGIN TESTING TORPEDOES SYSTEM!");
   Put_Line("Submariner: Errr... Admiral? We don't have any torpedoes. Or tubes for that matter.");
   Put_Line("The Admiral looks deeply into the submariner's eyes, only witnessing the sheer shock of a submarine having no torpedo systems");
   Put_Line("Admiral: ....Bugger!");
   Put_Line("");
   Put_Line("");
   Put_Line("");
   Put_Line("ALL FEATURES HAVE NOW BEEN TESTED! ENDING PROGRAM!");
   Put_Line("");

end Main;
